theme: jekyll-theme-cayman
name: Shawnee Summer Theatre 2019
site-title: Shawnee Summer Theatre 2019
description: Be a part of our biggest, most ambitious season yet
github:
  is_project_page: false
  
